apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-persistent-claim-gov
  namespace: govinda
spec:
  volumeMode: Filesystem
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Mi