kind: PersistentVolume
apiVersion: v1
metadata:
  name: log-persistent-volume-gov
  namespace: govinda
  labels:
    type: local
spec:
  volumeMode: Filesystem
  storageClassName: manual
  capacity:
    storage: 5500Mi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/mnt/logs"